# API Gateway Configuration

# Environment
environment: "development"
service_name: "api-gateway"
version: "v1.0.0"

# Server configuration
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  shutdown_timeout: 10s

# JWT configuration (for token validation)
jwt:
  secret: "development-auth-secret-key-change-in-production"
  issuer: "api-server-auth"
  expiration_time: 24h
  refresh_time: 168h
  algorithm: "HS256"

# Logging configuration
logging:
  level: "debug"
  format: "console"
  output: "stdout"

# Rate limiting
rate_limit:
  requests_per_second: 100
  burst_size: 200
  cleanup_interval: 5m

# CORS configuration
cors:
  allow_origins: ["*"]
  allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allow_headers: ["Origin", "Content-Length", "Content-Type", "Authorization"]
  expose_headers: ["X-Request-ID"]
  allow_credentials: false
  max_age: 12h

# Service URLs (can be overridden by environment variables)
services:
  auth_service_url: "http://auth-service:8081"
  user_service_url: "http://user-service:8082"