apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices
data:
  # Database Configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME_AUTH: "auth_db"
  DB_NAME_USER: "user_db"
  DB_SSL_MODE: "disable"
  
  # Service URLs
  AUTH_SERVICE_URL: "http://auth-service:8081"
  USER_SERVICE_URL: "http://user-service:8082"
  GATEWAY_SERVICE_URL: "http://api-gateway:8080"
  
  # Logger Configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  
  # Server Configuration
  GIN_MODE: "release"