apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices
type: Opaque
data:
  # Base64 encoded values
  # echo -n 'your-secret-value' | base64
  
  # Database password: 'password' -> cGFzc3dvcmQ=
  DB_PASSWORD: cGFzc3dvcmQ=
  
  # JWT secret key: 'your-super-secret-jwt-key-change-in-production' -> eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
  JWT_SECRET_KEY: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==