apiVersion: v1
kind: Secret
metadata:
  name: api-server-secrets
  namespace: api-server
  labels:
    app: api-server
    component: secrets
type: Opaque
data:
  # Base64 encoded secrets - CHANGE THESE IN PRODUCTION!
  # Default values for demonstration only
  
  # PostgreSQL credentials (postgres/postgres)
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  
  # Redis password (redis_secure_password)
  REDIS_PASSWORD: cmVkaXNfc2VjdXJlX3Bhc3N3b3Jk
  
  # JWT Secret (your-super-secret-jwt-key-for-production)
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1mb3ItcHJvZHVjdGlvbg==
  
  # Database URL for connection
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0Bwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvYXBpX3NlcnZlcj9zc2xtb2RlPWRpc2FibGU=

---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: api-server
  labels:
    app: api-server
    component: monitoring
type: Opaque
data:
  # Grafana admin password (admin)
  GRAFANA_ADMIN_PASSWORD: YWRtaW4=
  
  # Prometheus admin password (prometheus)
  PROMETHEUS_ADMIN_PASSWORD: cHJvbWV0aGV1cw==