# Development environment configuration
environment: development
service_name: api-server
version: v1.0.0

# Server configuration
server:
  host: localhost
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  shutdown_timeout: 10s
  tls_cert_file: ""
  tls_key_file: ""

# Database configuration
database:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: api_server_dev
  ssl_mode: disable
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 30m
  conn_max_idle_time: 15m

# JWT configuration
jwt:
  secret: your-super-secret-jwt-key-for-development
  issuer: api-server-dev
  expiration_time: 24h
  refresh_time: 168h # 7 days
  algorithm: HS256

# Rate limiting configuration
rate_limit:
  requests_per_second: 100.0
  burst_size: 200
  cleanup_interval: 5m

# CORS configuration
cors:
  allow_origins:
    - "http://localhost:3000"
    - "http://localhost:3001"
  allow_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
  allow_headers:
    - Origin
    - Content-Length
    - Content-Type
    - Authorization
    - X-Request-ID
  expose_headers:
    - X-Request-ID
  allow_credentials: true
  max_age: 12h

# Logging configuration
logging:
  level: debug
  format: console
  output: stdout
  disable_caller: false
  disable_stacktrace: false
  service_name: api-server
  service_version: v1.0.0

# Feature flags
features:
  enable_metrics: true
  enable_profiling: true
  enable_debug_endpoints: true
  enable_swagger: true

# Microservices configuration
services:
  auth_service:
    host: localhost
    port: 8081
    timeout: 30s
  user_service:
    host: localhost
    port: 8082
    timeout: 30s
  api_gateway:
    host: localhost
    port: 8080
    timeout: 30s