# User Service Configuration

# Environment
environment: "development"
service_name: "user-service"
version: "v1.0.0"

# Server configuration
server:
  host: "0.0.0.0"
  port: 8082
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  shutdown_timeout: 10s

# Database configuration
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database: "api_server"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 30m
  conn_max_idle_time: 5m

# JWT configuration
jwt:
  secret: "development-auth-secret-key-change-in-production"
  issuer: "api-server-auth"
  expiration_time: 24h
  refresh_time: 168h  # 7 days
  algorithm: "HS256"

# Logging configuration
logging:
  level: "debug"
  format: "console"
  output: "stdout"

# Rate limiting
rate_limit:
  requests_per_second: 10
  burst_size: 20
  cleanup_interval: 5m

# CORS configuration
cors:
  allow_origins: ["*"]
  allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allow_headers: ["Origin", "Content-Length", "Content-Type", "Authorization"]
  expose_headers: ["X-Request-ID"]
  allow_credentials: false
  max_age: 12h